extends:
  - eslint:recommended
  - google
  - plugin:flowtype/recommended
  - plugin:vue/recommended
parser: "vue-eslint-parser"
parserOptions:
  parser: babel-eslint
# 增加了babel-eslint之后，下面的这些设置可以注释掉了
# parserOptions:
#  "ecmaVersion": 6
#  "sourceType": "module"
plugins:
  - "flowtype"
  - "html"
env:
  "browser": true
  "node": true
  "es6": true
rules:
  indent:
    - "error"
    - 2
    -
      SwitchCase: 1
  no-console: ["error", { allow: ["warn", "error", "log", "debug"] }]
  max-len: ["error", {code: 160}]
